**Usando o markdown**

Markdown são usados para comentários e enunciados. Pesquise na web como usá-los

In [7]:
# iniciando com python
# https://www.facom.ufu.br/~wendelmelo/meu_material/introducao_programacao_python_wendel_melo.pdf

x = 2 +6
a = 1
print(x)
print(a)

8
1


https://www.facom.ufu.br/~wendelmelo/pythontw201901/aula_numpy.txt

numerical python
o propósito do numpy é facilitar computação numérica, científica e matricial

Numpy disponibiliza duas classes principais:
array: array de qualquer dimensão
matrix: representa matrizes de duas dimensões (linhas e colunas)

Instalar o pacote (shell):
pip3 install -U numpy

import numpy as np
A = np.matrix(  [ [1,2], [3,4]  ]    )


In [8]:
import numpy as np
A = np.matrix(  [ [4,3 ,2 ,1 ], [8,7,6,5],[ 12,11,10,9]  ] )   
A

matrix([[ 4,  3,  2,  1],
        [ 8,  7,  6,  5],
        [12, 11, 10,  9]])

In [9]:
#a variável A aponta para uma matriz de duas linhas e duas colunas
type(A)


numpy.matrix

In [10]:
#acessando um elemento da matriz
print("Matrix")
print(A)
print("Acessos")
print(A[0, 2])#acessa o elemento na linha 0 e na coluna 1
print(A[2]) #acessa a linha 1 da matriz
print(A[2,:]) #acessa a linha 1 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas
print(A[:, 1])  #acessa toda a coluna 0 da matriz. Dois pontos significa "todas" - se na primeira dimensão, todas as linhas



Matrix
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Acessos
2
[[12 11 10  9]]
[[12 11 10  9]]
[[ 3]
 [ 7]
 [11]]


In [11]:
#acessando um elemento da matriz com : (python slice) ==> inicio:fim:passo
# doc completa: https://docs.python.org/3/library/stdtypes.html#typesseq
# se início é omitido, fica com a coluna 0. Ex: :1:1
# se fim é omitido, vai até o final da dimensão. Ex 1::1
# se o passo é omitido, é assumido valor 1. Ex: 1:2
print("Matrix")
print(A)
print("Acesso [0:2,1]")
print(A[0:1, 0])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e na coluna 1
print("Acessos [0:2,1:4:2]")
print(A[0:1, 0:3:1])#acessa o elemento na linha 0 até a linha 1 (ou seja, 2-1 = 1) e iniciando na coluna 1, pulando uma coluna  e indo até a colune 4-1=3
print("Mostrando a matriz com as linhas reversas")
print(A[::-1,:]) 



Matrix
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Acesso [0:2,1]
[[4]]
Acessos [0:2,1:4:2]
[[4 3 2]]
Mostrando a matriz com as linhas reversas
[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [6]:

#a função zeros gera um array de zeros
Z = np.zeros(  (5,5)    )
Z


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#podemos gerar matrizes de números aleatórios
import numpy.random as npr
N = np.matrix(   npr.randint(0, 10, (2, 2)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N

matrix([[1, 4],
        [4, 2]])

In [13]:
#gernado outra matriz
N = np.matrix(   npr.randint(0, 10, (3, 3)  )    )  #gera matriz de numeros inteiros aleatorios entre -10 e 10, tendo 3 linhas e 2 colunas
N


matrix([[9, 4, 7],
        [7, 4, 9],
        [0, 4, 2]])

In [14]:
# Lembre que python é orientado a objetos. Assim uma simples atribuições entre duas matrizes faz com que abas apontem para o mesmo objeto
B=A
print(A)
print(B)

print("Mudando o valor de A - veja que B foi modificado também")
A[0,0] = -20
print(A)
print(B)

print("Mudando o valor de B - veja que A foi modificado também")
B[0,0] = 40
print(A)
print(B)



[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Mudando o valor de A - veja que B foi modificado também
[[-20   3   2   1]
 [  8   7   6   5]
 [ 12  11  10   9]]
[[-20   3   2   1]
 [  8   7   6   5]
 [ 12  11  10   9]]
Mudando o valor de B - veja que A foi modificado também
[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [15]:
# podemos criar uma matriz copiando de uma outra matriz,
C = np.matrix(A)
print(A)
print(C)
print("Mudando o valor de A - veja que C não será afetada")
A[0,0] = 60
print(A)
print(C)


print("Mudando o valor de C - veja que A não será afetada")
C[0,0] = 40
print(A)
print(C)

[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Mudando o valor de A - veja que C não será afetada
[[60  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Mudando o valor de C - veja que A não será afetada
[[60  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [35]:
#podemos operar com blocos de matrizes
M = np.matrix(C)
print("Matriz M: ")
print(M)
print("Matriz N: ")
print(N)
#M[ 0:3,  2:4  ] = N
M[ 0:3,  0:3  ] = N
print("Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 ")
print(M)

Matriz M: 
[[40  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
Matriz N: 
[[9 4 7]
 [7 4 9]
 [0 4 2]]
Matriz M após a atribuição em bloco: da linha zero até a linha 3, da coluna 2 até a 4 
[[9 4 7 1]
 [7 4 9 5]
 [0 4 2 9]]


In [36]:
#podemos fazer operações diversas com matrizes
#criando uma matriz identidade (coluna com diagonal igual a 1)
B = np.matrix(   np.eye(3,3)    )
print(B)
print(np.matrix(   np.eye(8,8)    ))



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
A = np.matrix([[1 ,2], [3 ,4]])
print(A)
print(B)
#multiplicando a matriz A por um escalar
A = 4*A
A



[[1 2]
 [3 4]]
[[16.  0.  0.]
 [ 0. 16.  0.]
 [ 0.  0. 16.]]


matrix([[ 4,  8],
        [12, 16]])

In [43]:
#somando matrizes
A = np.matrix(np.eye(3,3))
B = np.matrix(   [[1,1,1],[2,2,2],[3,3,3]]    )
print(A)
print(B)
C = A + B
C


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


matrix([[2., 1., 1.],
        [2., 3., 2.],
        [3., 3., 4.]])

In [44]:
#multiplicando matrizes

print(A)
print(B)

D = A * B
D


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


matrix([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [46]:
#podemos calcular potencia de matrizes

print(A)
print(B)

E = A**3 #equivale a E = A * A (multiplica a matriz por ela mesma)
E


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]


matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [47]:
#podemos calcular a inversa de uma matriz

print(A)
Ainversa = A**-1
print(Ainversa)
print(A * Ainversa)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [48]:
#podemos calcular a matriz transposta
A
print(A)
print(np.transpose(A))


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [50]:
#a função trace que calcula o traço da matriz (a soma dos elementos da diagonal principal)

print(B)
np.trace(B)


[[1 1 1]
 [2 2 2]
 [3 3 3]]


np.int64(6)

In [53]:
#podemos concatenar matrizes
#por coluna: hstack

print(B)
print(C)
np.hstack( (B, C) )


[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[2. 1. 1.]
 [2. 3. 2.]
 [3. 3. 4.]]


matrix([[1., 1., 1., 2., 1., 1.],
        [2., 2., 2., 2., 3., 2.],
        [3., 3., 3., 3., 3., 4.]])

In [21]:
#concatenando por linhas (vertical): vstack

print(A)
print(B)
np.vstack(  (A,B)   )


[[1 1]
 [2 3]]
[[4. 0.]
 [0. 4.]]


matrix([[1., 1.],
        [2., 3.],
        [4., 0.],
        [0., 4.]])

In [54]:
#existem funções que se aplicam a todos os elementos de uma matriz

print(A)

np.sqrt(A)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


matrix([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])